%
% This MATLAB script is the command line equivalent of the exact
% linearization tab in linear analysis tool with current settings.
% It produces the exact same linearization results as hitting the Linearize button.

% MATLAB(R) file generated by MATLAB(R) 9.4 and Simulink Control Design (TM) 5.1.
%
% Generated on: 29-Oct-2022 17:53:38

%% Specify the model name
model = 'Lab1';

%% Specify the analysis I/Os
% Get the analysis I/Os from the model
io = getlinio(model);

%% Specify the operating point
% Use the model initial condition
op = operpoint(model);


%% Linearize the model
sys = linearize(model,io,op);

%% Plot the resulting linearization
step(sys)
tf(sys)
